language: node_js
node_js: '11'
script: npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_373965b62ca2_key -iv $encrypted_373965b62ca2_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@47.106.132.31 -o StrictHostKeyChecking=no 'cd ~/webroot/163music/ && git pull && cnpm i && npm run build && pm2 restart server'
